config/routes.rb
Rails.application.routes.draw do
  # resources :comments
  
  # get 'articles/new'
  # get 'articles/index'
  resources :articles do
    resources :comments
  end

  devise_for :autors

  get "contacto", to: 'statics#contact'
  get "nosotros", to: 'statics#about_us'

  get "inicio", to: 'articles#index'
  root "articles#index"

  get "*path" => redirect('/')

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :autor
  has_many :comments, dependent: :destroy
  validates :title, presence: { :message => "no puede estar vacio"}
  validates :content, presence: { :message => "no puede estar vacio"}, length: {minimum: 50, :message => "es demasiado corto, mínimo 50 caracteres"}
end

app/models/autor.rb
class Autor < ApplicationRecord
  has_many :articles
  # Include default devise modules. Others available are:

  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #:ConfirmarElEmail, :bloquearDespuesDeIntentos, :CerrarSesionDespuesDeTiempo, :guardarIp,
  
devise :database_authenticatable, :registerable,
       #:compararContraseñaEnbase de datos, :creaTodoElSign_up
       :recoverable, :rememberable, :validatable
       #:RecuperarContraseña, :checkRecuerdame, :validacionesPorEjemploDeFormato
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_autor!, except: %i[index show]  
  before_action :correct_autor, only: %i[edit update destroy]  
  before_action :set_article, only: %i[show edit update destroy]

  def show
  end

  def index
    @articles = Article.all.order("created_at DESC")
  end

  def new
    @article = current_autor.articles.build
  end

  def create
    @article = current_autor.articles.build(article_params)
    if @article.save
      redirect_to @article
    else
      render "new"
    end
  end

  def edit 
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Articulo modificado correctamente"
      redirect_to @article
    else
      render "edit"
    end
  end

  def destroy
    @article.destroy!
    redirect_to articles_path, :notice => "Autor eliminado correctamente"
  end

  private

    def article_params
      params.require(:article).permit(:title, :content, :autor_id)
    end

    def set_article
      @article = Article.find(params[:id])
    end

    def correct_autor
      @article = current_autor.articles.find_by(id: params[:id])
      redirect_to articles_path, notice: "No estas autorizado a editar este artículo" if @article.nil?
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # POST /comments or /comments.json
  def create
    @article = Article.find(params[:article_id])  
    @comment = @article.comments.create(comment_params)

    redirect_to @article
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy!

    redirect_to @article
  end

  private

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:name, :text, :article_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def contact
  end

  def about_us
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/articles/_form.html.erb
<%# creamos el formulario en parcial para poder utilizarlo en la vista new y edit sin repetirlo %>

<%= form_for @article do |form| %> <%# este es el helper para la creacion de formularios en ruby %>
  <% if @article.errors.any? %>  <%#  insertamos un condicional que imprimirá cualquier tipo de error que se genere%>
    <div style="color: red">
      <h2> Se han producido los siguientes errores: </h2>
      <ul>
        <% @article.errors.each do |error| %> <%#  aqui iteramos e imprimimos el array de errores que se genera%>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :title %> <br>  <%# form. esta definido en el inicio del formulario y hace referencia el formulario mismo %>
  <%= form.text_field :title %> <br> <%# de esta forma relacionamos cada elemento con el formulario %>

  <%= form.label :content %> <br>
  <%= form.text_area :content %> <br>

  <%= form.submit yield(:button)%>

<% end %>

app/views/articles/edit.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-8 text-center">
      <h1>Articulos#edit</h1>
      <p>Find me in app/views/articulos/edit.html.erb</p>

      <% provide(:button, "modificar articulo") %>
      <%= render "form" %>
    
    </div>
  </div>

  <div class="row pt-5">
    <div class="col">
      <%= link_to "índice de articulos", articles_path %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-8 text-center">
      <h1>Articulos#index</h1>
    </div>
  </div>

  <div class="row pt-5">
    <div class="col">
      <% @articles.each do |article| %>
        <h2><%= link_to article.title, article %></h2>
        <p><small>Creado el <%= article.created_at.strftime("%d-%m-%y") %></small></p>
        <p><%= article.content.truncate_words(30) %></p>
      <% end %>
    </div>
  </div>          

  <div class="row pt-5">
    <div class="col">
      <%= link_to "nuevo articulo", new_article_path %>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-8 text-center">
      <h1>Articulos#new</h1>
      <p>Find me in app/views/articulos/new.html.erb</p>

      <% provide(:button, "crear articulo") %>
      <%= render "form" %>
    </div>
  </div>

  <div class="row pt-5">
    <div class="col">
      <%= link_to "índice de articulos", articles_path %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-8 text-center">
      <%# aqui estamos accediendo a cada uno de los metodos de la variable de instancia, que a su vez son las columnas o atributos, de cada entidad o tabla de la base de datos %>
      <h1> <%= @article.title %> </h1> 
      <p> <%=@article.created_at.strftime("%d-%m-%y") %></p> <%# .strftime() es un metodo de ruby para darle formato a las fechas  %>
      <p> <%= @article.content %> </p> 
    </div>
  </div>

  <div class="row justify-content-center text-center pt-5">
    <div class="col">
      <%= link_to "índice de articulos", articles_path %>
    </div>
      <div class="col">
        <% if autor_signed_in? %>
         <%= link_to "editar Articulo", edit_article_path(@article) %>
        <% end%>
      </div>
      <div class="col">
        <% if autor_signed_in? %>
         <%= button_to "eliminar Articulo", @article, method: :delete, data: {confirm: "seguro que quieres eliminar el articulo?"} %>
        <% end%>
      </div>
  </div>
  <!--
    <% @article.comments.each do |comment| %>
      <%= comment.name %>
      <%= comment.text %>
    <% end%>
  -->
  <p> <%= @article.comments.count%> <%= @article.comments.count > 1 ? "Comentarios" : "Comentario" %> </p>
  <%= render @article.comments %> <%# este render junto con el partial utilizado sustituyen el cilo each comentado arriba%>

  <p> Deja tu comentario </p>
  <br>
  <%= render "comments/form" %>

</div>

app/views/comments/_comment.html.erb
<div>
  <p>
    <%= comment.name %>
  <p>
  <p>
    <%= comment.text %>
  <p>
  <p>
    <small>Creado el <%= comment.created_at.strftime("%d-%m-%Y") %> </small>
  <p>
  <%= button_to "Eliminar", [comment.article, comment], :method => :delete, data: { confirm: "Seguro que quieres eliminar este comentario?"} %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |form| %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/home/index.html.erb
<%= provide(:title, "Inicio") %>
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  </head>

  <body>

    <%= render "shared/header" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <div class="container-fluid">
      <%= yield %>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_header.html.erb
<%= link_to "Inicio", inicio_path%>
<%= link_to "Contacto", contacto_path%>
<%= link_to "Nosotros", nosotros_path%>


<%= link_to "Iniciar sesión", new_autor_session_path%>
<%= link_to "Unirse", new_autor_registration_path%>
<%= button_to "Cerrar sesión", destroy_autor_session_path, method: :delete, data: { confirm: "Are you sure to delete?" }%>
<%= link_to "Editar autor", edit_autor_registration_path%>

app/views/statics/about_us.html.erb
<%= provide(:title, "Nosotros") %>
<h1>Statics#about_us</h1>
<p>Find me in app/views/statics/about_us.html.erb</p>

app/views/statics/contact.html.erb
<%= provide(:title, "Contacto") %>
<h1>Statics#contact</h1>
<p>Find me in app/views/statics/contact.html.erb</p>